task.spawn(function()
local ExecutorSettings = {toggleKey = Enum.KeyCode.Insert, visible = false, theme = {primary = Color3.fromRGB(138, 43, 226), secondary = Color3.fromRGB(75, 0, 130), background = Color3.fromRGB(20, 20, 25), surface = Color3.fromRGB(30, 30, 35), text = Color3.fromRGB(255, 255, 255)}}
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local gui = Instance.new("ScreenGui") gui.Name = "JulesExecutor" gui.ResetOnSpawn = false gui.DisplayOrder = 10000 gui.IgnoreGuiInset = true if cg then gui.Parent = cg else gui.Parent = game:GetService("StarterGui") end
local mainFrame = Instance.new("Frame") mainFrame.Name = "MainFrame" mainFrame.Size = UDim2.new(0, 600, 0, 400) mainFrame.Position = UDim2.new(0.5, -300, 0.5, -200) mainFrame.BackgroundColor3 = ExecutorSettings.theme.background mainFrame.BorderSizePixel = 0 mainFrame.Visible = false mainFrame.Parent = gui
local mainCorner = Instance.new("UICorner") mainCorner.CornerRadius = UDim.new(0, 12) mainCorner.Parent = mainFrame
local mainStroke = Instance.new("UIStroke") mainStroke.Color = ExecutorSettings.theme.primary mainStroke.Thickness = 2 mainStroke.Parent = mainFrame
local topBar = Instance.new("Frame") topBar.Size = UDim2.new(1, 0, 0, 40) topBar.BackgroundColor3 = ExecutorSettings.theme.surface topBar.BorderSizePixel = 0 topBar.Parent = mainFrame
local topBarCorner = Instance.new("UICorner") topBarCorner.CornerRadius = UDim.new(0, 12) topBarCorner.Parent = topBar
local topBarFix = Instance.new("Frame") topBarFix.Size = UDim2.new(1, 0, 0, 20) topBarFix.Position = UDim2.new(0, 0, 1, -20) topBarFix.BackgroundColor3 = ExecutorSettings.theme.surface topBarFix.BorderSizePixel = 0 topBarFix.Parent = topBar
local title = Instance.new("TextLabel") title.Size = UDim2.new(0, 200, 1, 0) title.Position = UDim2.new(0, 15, 0, 0) title.BackgroundTransparency = 1 title.Text = "Jules Executor" title.TextColor3 = ExecutorSettings.theme.text title.TextSize = 18 title.Font = Enum.Font.GothamBold title.TextXAlignment = Enum.TextXAlignment.Left title.Parent = topBar
local buttonContainer = Instance.new("Frame") buttonContainer.Size = UDim2.new(0, 100, 1, 0) buttonContainer.Position = UDim2.new(1, -110, 0, 0) buttonContainer.BackgroundTransparency = 1 buttonContainer.Parent = topBar
local buttonLayout = Instance.new("UIListLayout") buttonLayout.FillDirection = Enum.FillDirection.Horizontal buttonLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right buttonLayout.VerticalAlignment = Enum.VerticalAlignment.Center buttonLayout.Padding = UDim.new(0, 5) buttonLayout.Parent = buttonContainer
local function createIconButton(name, icon, callback) local button = Instance.new("TextButton") button.Size = UDim2.new(0, 30, 0, 30) button.BackgroundColor3 = ExecutorSettings.theme.surface button.BorderSizePixel = 0 button.Text = "" button.Parent = buttonContainer local corner = Instance.new("UICorner") corner.CornerRadius = UDim.new(0, 6) corner.Parent = button local iconLabel = Instance.new("TextLabel") iconLabel.Size = UDim2.new(1, 0, 1, 0) iconLabel.BackgroundTransparency = 1 iconLabel.Text = icon iconLabel.TextColor3 = ExecutorSettings.theme.text iconLabel.TextSize = 16 iconLabel.Font = Enum.Font.GothamBold icon Label.Parent = button button.MouseButton1Click:Connect(callback) button.MouseEnter:Connect(function() TweenService:Create(button, TweenInfo.new(0.2), {BackgroundColor3 = ExecutorSettings.theme.primary}):Play() TweenService:Create(iconLabel, TweenInfo.new(0.2), {TextSize = 18}):Play() end) button.MouseLeave:Connect(function() TweenService:Create(button, TweenInfo.new(0.2), {BackgroundColor3 = ExecutorSettings.theme.surface}):Play() TweenService:Create(iconLabel, TweenInfo.new(0.2), {TextSize = 16}):Play() end) return button end
createIconButton("Close", "X", function() ExecutorSettings.visible = false TweenService:Create(mainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.In), {Position = UDim2.new(0.5, -300, -0.5, -200)}):Play() task.wait(0.3) mainFrame.Visible = false end)
createIconButton("Settings", "", function() end)
local codeBox = Instance.new("ScrollingFrame") codeBox.Size = UDim2.new(1, -20, 1, -120) codeBox.Position = UDim2.new(0, 10, 0, 50) codeBox.BackgroundColor3 = ExecutorSettings.theme.surface codeBox.BorderSizePixel = 0 codeBox.ScrollBarThickness = 6 codeBox.CanvasSize = UDim2.new(0, 0, 0, 0) codeBox.AutomaticCanvasSize = Enum.AutomaticSize.Y codeBox.Parent = mainFrame
local codeBoxCorner = Instance.new("UICorner") codeBoxCorner.CornerRadius = UDim.new(0, 8) codeBoxCorner.Parent = codeBox
local codeInput = Instance.new("TextBox") codeInput.Size = UDim2.new(1, -10, 1, 0) codeInput.Position = UDim2.new(0, 5, 0, 5) codeInput.BackgroundTransparency = 1 codeInput.Text = "-- Jules Executor\nprint('Hello World!')" codeInput.TextColor3 = ExecutorSettings.theme.text codeInput.TextSize = 14 codeInput.Font = Enum.Font.Code codeInput.TextXAlignment = Enum.TextXAlignment.Left codeInput.TextYAlignment = Enum.TextYAlignment.Top codeInput.MultiLine = true codeInput.ClearTextOnFocus = false codeInput.TextWrapped = false codeInput.Parent = codeBox
codeInput:GetPropertyChangedSignal("Text"):Connect(function() local lines = #string.split(codeInput.Text, "\n") codeInput.Size = UDim2.new(1, -10, 0, math.max(250, lines * 18 + 10)) end)
local bottomBar = Instance.new("Frame") bottomBar.Size = UDim2.new(1, -20, 0, 50) bottomBar.Position = UDim2.new(0, 10, 1, -60) bottomBar.BackgroundTransparency = 1 bottomBar.Parent = mainFrame
local bottomLayout = Instance.new("UIListLayout") bottomLayout.FillDirection = Enum.FillDirection.Horizontal bottomLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center bottomLayout.VerticalAlignment = Enum.VerticalAlignment.Center bottomLayout.Padding = UDim.new(0, 10) bottomLayout.Parent = bottomBar
local function createActionButton(name, text, icon, callback) local button = Instance.new("TextButton") button.Size = UDim2.new(0, 150, 0, 40) button.BackgroundColor3 = ExecutorSettings.theme.primary button.BorderSizePixel = 0 button.Text = "" button.Parent = bottomBar local corner = Instance.new("UICorner") corner.CornerRadius = UDim.new(0, 8) corner.Parent = button local iconLabel = Instance.new("TextLabel") iconLabel.Size = UDim2.new(0, 30, 1, 0) iconLabel.BackgroundTransparency = 1 iconLabel.Text = icon iconLabel.TextColor3 = ExecutorSettings.theme.text iconLabel.TextSize = 18 iconLabel.Font = Enum.Font.GothamBold iconLabel.Parent = button local textLabel = Instance.new("TextLabel") textLabel.Size = UDim2.new(1, -30, 1, 0) textLabel.Position = UDim2.new(0, 30, 0, 0) textLabel.BackgroundTransparency = 1 textLabel.Text = text textLabel.TextColor3 = ExecutorSettings.theme.text textLabel.TextSize = 16 textLabel.Font = Enum.Font.GothamBold textLabel.Parent = button button.MouseButton1Click:Connect(callback) button.MouseEnter:Connect(function() TweenService:Create(button, TweenInfo.new(0.2), {BackgroundColor3 = ExecutorSettings.theme.secondary, Size = UDim2.new(0, 155, 0, 42)}):Play() end) button.MouseLeave:Connect(function() TweenService:Create(button, TweenInfo.new(0.2), {BackgroundColor3 = ExecutorSettings.theme.primary, Size = UDim2.new(0, 150, 0, 40)}):Play() end) return button end
createActionButton("Execute", "Execute", "", function() local code = codeInput.Text if code and #code > 0 then task.spawn(function() local func, err = env.loadstring(code) if func then local success, execErr = pcall(func) if not success then warn("[Jules] Execution Error: " .. tostring(execErr)) end else warn("[Jules] Compile Error: " .. tostring(err)) end end) end end)
createActionButton("Clear", "Clear", "", function() codeInput.Text = "" end)
createActionButton("Paste", "Paste", "", function() end)
local dragStart, startPos, dragging = nil, nil, false
topBar.InputBegan:Connect(function(input) if input.UserInputType == Enum.UserInputType.MouseButton1 then dragging = true dragStart = input.Position startPos = mainFrame.Position end end)
topBar.InputEnded:Connect(function(input) if input.UserInputType == Enum.UserInputType.MouseButton1 then dragging = false end end)
UserInputService.InputChanged:Connect(function(input) if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then local delta = input.Position - dragStart mainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y) end end)
local function toggleUI() ExecutorSettings.visible = not ExecutorSettings.visible mainFrame.Visible = true if ExecutorSettings.visible then mainFrame.Position = UDim2.new(0.5, -300, -0.5, -200) TweenService:Create(mainFrame, TweenInfo.new(0.4, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {Position = UDim2.new(0.5, -300, 0.5, -200)}):Play() else TweenService:Create(mainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.In), {Position = UDim2.new(0.5, -300, -0.5, -200)}):Play() task.wait(0.3) mainFrame.Visible = false end end
UserInputService.InputBegan:Connect(function(input, gameProcessed) if not gameProcessed and input.KeyCode == ExecutorSettings.toggleKey then toggleUI() end end)
print("[Jules] Executor UI created! Press INSERT to toggle")
end)
